# Generated by Django 5.1.2 on 2024-10-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("grade", models.CharField(max_length=2)),
                ("gender", models.CharField(max_length=6)),
                ("address", models.TextField()),
                ("contact_number", models.CharField(max_length=15)),
            ],
        ),
    ]
