# Generated by Django 5.1.2 on 2024-10-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_exams_examscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exams",
            name="id",
        ),
        migrations.RemoveField(
            model_name="examscore",
            name="id",
        ),
        migrations.AddField(
            model_name="examscore",
            name="score_value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exams",
            name="exam_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="exams",
            name="exam_name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="examscore",
            name="exam_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="api.exams",
            ),
        ),
        migrations.AlterField(
            model_name="examscore",
            name="score_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="examscore",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.student"
            ),
        ),
    ]
