# Generated by Django 5.1.2 on 2024-10-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_exams_id_remove_examscore_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examscore",
            name="exam_id",
        ),
        migrations.RemoveField(
            model_name="examscore",
            name="student_id",
        ),
        migrations.DeleteModel(
            name="Exams",
        ),
        migrations.DeleteModel(
            name="ExamScore",
        ),
    ]
