# Generated by Django 5.1.2 on 2024-10-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_exams_examscore"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examscore",
            old_name="score",
            new_name="score_value",
        ),
    ]
