# Generated by Django 5.1.2 on 2024-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_score_examscore_score_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exams",
            name="exam_name",
        ),
        migrations.AddField(
            model_name="exams",
            name="maths",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exams",
            name="science",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exams",
            name="social",
            field=models.IntegerField(default=0),
        ),
    ]
